services:

  wordpress:
    container_name: sumup-wordpress
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./xdebug

    ports:
      - "80:80"

    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: mydbname
      WORDPRESS_DB_USER: mydbuser
      WORDPRESS_DB_PASSWORD: mydbpassword
      # Set the XDEBUG_CONFIG as described here: https://xdebug.org/docs/remote
      XDEBUG_CONFIG: client_host=172.19.0.5

    depends_on:
      - db

    volumes:
      - /opt/projects/wpd/www:/var/www/html
      - ./:/var/www/html/wp-content/plugins/sumup-plugin-for-woocommerce
      - ./apache-config.conf:/etc/apache2/conf-enabled/apache-cors.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      backend-sumup:
        ipv4_address: 172.19.0.5
      frontend-sumup: {}


  db:
    container_name: mysql-sumup-wordpress
    image: mysql:8.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: mydbrootpassword
      MYSQL_DATABASE: mydbname
      MYSQL_USER: mydbuser
      MYSQL_PASSWORD: mydbpassword
      innodb_fast_shutdown: 1

    ports:
      -  "3306:3306"

    volumes:
      - /opt/projects/wpd/mysql:/var/lib/mysql

    networks:
      backend-sumup:
        ipv4_address: 172.19.0.4

networks:
  frontend-sumup: {}
  backend-sumup:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24

